services:
  - type: web
    name: ai-summary-backend
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: ALLOWED_ORIGINS
        sync: false
      - key: PORT
        value: "10000"
      - key: HOST
        value: "0.0.0.0"
      - key: DEBUG
        value: "False"

  - type: static
    name: ai-summary-frontend
    rootDir: frontend
    buildCommand: npm ci && npm run build
    staticPublishPath: build
    envVars:
      - key: REACT_APP_API_BASE_URL
        sync: false
